// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPmxBY6G_U0BFacw5zbMSOljEiarnmAbE',
    appId: '1:893804085902:web:574a809182e215e3763fdf',
    messagingSenderId: '893804085902',
    projectId: 'trackrr-acc27',
    authDomain: 'trackrr-acc27.firebaseapp.com',
    storageBucket: 'trackrr-acc27.firebasestorage.app',
    measurementId: 'G-Q1R9817X4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysoDwHaopizU1dJK5G39HjSL0fOPwb1w',
    appId: '1:893804085902:android:dfd50d56ed984513763fdf',
    messagingSenderId: '893804085902',
    projectId: 'trackrr-acc27',
    storageBucket: 'trackrr-acc27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybqwzXOgbzW_HjjHKn0B3kDYbnd6wbnc',
    appId: '1:893804085902:ios:43e5f374b9268a35763fdf',
    messagingSenderId: '893804085902',
    projectId: 'trackrr-acc27',
    storageBucket: 'trackrr-acc27.firebasestorage.app',
    iosBundleId: 'com.example.parcelTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybqwzXOgbzW_HjjHKn0B3kDYbnd6wbnc',
    appId: '1:893804085902:ios:43e5f374b9268a35763fdf',
    messagingSenderId: '893804085902',
    projectId: 'trackrr-acc27',
    storageBucket: 'trackrr-acc27.firebasestorage.app',
    iosBundleId: 'com.example.parcelTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPmxBY6G_U0BFacw5zbMSOljEiarnmAbE',
    appId: '1:893804085902:web:1841c7b6fc02cee4763fdf',
    messagingSenderId: '893804085902',
    projectId: 'trackrr-acc27',
    authDomain: 'trackrr-acc27.firebaseapp.com',
    storageBucket: 'trackrr-acc27.firebasestorage.app',
    measurementId: 'G-WTQCSC8XNE',
  );
}
